apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wgojyaq5s-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:e7d29c4194d12cc2919610d5f928b8a6103cabcf@sha256:2f342a8da4de5dc4a698a876eecf78f87f4a604a901d7f18b7bb38c180810e5e
          name: container-image
