apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wgojyaq5s-nodejs 
  janus-idp.io/tekton: wgojyaq5s-nodejs
  backstage.io/kubernetes-id: wgojyaq5s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgojyaq5s-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml